#!/usr/bin/env Rscript

options(scipen=20, digits=4)

# Load required packages (install these if needed)
lapply(c("data.table","lubridate"), require, character.only=T)

getRecordsWithStatus <- function(dt, status) {

    # Build column names (becuase I excluded them from the data file)
    columnnames <- c("date", "time", "x-edge-location", "sc-bytes", "c-ip", "cs-method", "cs(Host)", "cs-uri-stem", 
                      "sc-status", "cs(Referer)", "cs(User-Agent)", "cs-uri-query", "cs(Cookie)", "x-edge-result-type",
                      "x-edge-request-id", "x-host-header", "cs-protocol", "cs-bytes", "time-taken")

    # Set the column names
    setnames(dt, columnnames)

    # Write results
    write.table(dt[`sc-status`==status], paste("output/", status, ".csv"), row.names=FALSE, col.names=FALSE, append=TRUE)

}

# Read status code from command line args
args <- commandArgs(trailingOnly = TRUE)
status <- args[1]

dir.create("output")

# Get log files
files <- list.files(path="cf-logs", pattern="*", full.names=T, recursive=FALSE)

# Loop through files
lapply(files, function(file) {
    # Read data from file
    dt <- fread(file, header=FALSE, verbose=TRUE, skip=2)
    getRecordsWithStatus(dt, status)
})